apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r6jamwm4g-go
  janus-idp.io/tekton: r6jamwm4g-go
  backstage.io/kubernetes-id: r6jamwm4g-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: r6jamwm4g-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
